#name: CI/CD - BUILD
#
#on:
#  pull_request:
#    branches: [develop]
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Build the rust code
#        run : cargo build --verbose
#      - name: Run the tests
#        run : cargo test --verbose
#
